### ISSUE TITLE
project-rails-keyword-face not defined

### ISSUE THREAD

**Issue by brettatoms** [asok/projectile-rails#97] opened 2016-06-27 12:52 UTC
Upgraded today and font-lock is broken for rails files.  Seeing this in `*Messages*`:

```
Error during redisplay: (jit-lock-function 1) signaled (void-variable projectile-rails-keyword-face)
Error during redisplay: (jit-lock-function 520) signaled (void-variable projectile-rails-keyword-face)
Error during redisplay: (jit-lock-function 1059) signaled (void-variable projectile-rails-keyword-face)
```

**Comment by asok** [comment] 2016-06-27 13:47
@brettatoms thanks for reporting.
Please try installing now from the master branch and let me know if the issue is fixed for you.

**Comment by brettatoms** [comment] 2016-06-27 14:34
@asok I think this might be a conflict with the spacemacs `ruby-on-rails` layer.  When I install `projectile-rails` directly without the spacemacs layer its seems to work fine.  Could it be a problem with autoloading the the `defer: t` from `use-package`?

**Comment by nandryshak** [comment] 2016-06-27 19:31
@brettatoms @asok Mine is broken as well and I don't use spacemacs.

**Comment by asok** [comment] 2016-06-27 20:32
@brettatoms, @nandryshak it should be fixed. Please let me know if not.

**Closed** 2016-06-27 20:31 UTC

**Comment by brettatoms** [comment] 2016-06-27 22:01
@asok Works for me, thanks!

**Comment by nandryshak** [comment] 2016-06-28 13:34
@asok Mine is fixed too, thank you!
